title: Donghoon Shin
author:
  name: Donghoon Shin
  email: dhoon@uw.edu
description: > # this means to ignore newlines until "show_excerpts:"
  Donghoon Shin is a first-year Ph.D. student in HCDE at the Unviersity of Washington

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
plugins:
 - jekyll-feed
 - jekyll-seo-tag

theme: minima