project:
  - title: DrawTime
    image: drawtime_p.png
    detail: >
      <p> The project was designed to help teenagers develop better behaviors by maintaining a virtual self, which aided in effective time and emotional management. Launched in 2019, it reached 10,000 active users in six months. However, due to everyone's busy schedules, we couldn't maintain it :/ </p>

      <img src='site.baseurl/assets/images/project/drawtime_dl.png' class='img-responsive' alt='keyscreen of our system'>

      <p style='text-align: center;'><b>Our system</b></p>

      <hr>

      <p><b>[My role in this project]</b><br>Leading the project of a three-person team,UI design, and front-end development.</p>
    tags:
      - Personal informatics
      - Behavior Change
      - products
      - 1,0000 users
    description: >-
      Project to help teenagers behaviors change.
    id: DrawTime
  - title: Crypto Email:Metamail
    image: metamail.png
    detail: >
      <p> We created a Crypto Email service, one of the first on the market. While the exact need for it wasn't clear, the popularity of web3  help us attracted grant funding. I'm still considering what the real value of the project might be. Yet, I see the blockchain as promising for other uses, like the gig economy.</p>
      <img src='site.baseurl/assets/images/project/metamail_d.png' class='img-responsive' alt='keyscreen of our system'>


      <hr>

      <p><b>[My role in this project]</b><br>Core member of a four-person startup team.</p>
    tags:
      - Blockchain
      - Products
      - 1,0000 users
    description: >-
      Crypto Email
    id: design_card
  - title:  Online companion learning.
    image: sds_s.png
    detail: >
     <p> </p>

      <img src='site.baseurl/assets/images/project/sdsp.png' class='img-responsive' alt=''>

      <p style='text-align: center;'><b>An example of causal pathway diagram (CPD)</b></p>

      <hr>

      <p><b>[My role in this project]</b><br>Leading the project/p>
    tags:
      - Research
      - Behavoir Change

    description: >-
      Online companion learning.
  - title: ICOOBOOK
    image: icon1.png
    detail: >

      <img src='site.baseurl/assets/images/project/icon2.png' class='img-responsive' alt='keyscreen of our system'>

      <p style='text-align: center;'><b>An example of causal pathway diagram (CPD)</b></p>

      <hr>

      <p><b>[My role in this project]</b><br>Building a system</p>
    tags:
      - Research
      - Products
  
    description: >-
      ICOOBOOK    